name: lupin
description: "AI Video Generator"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_it: ^8.2.0
  get_storage: ^2.1.1
  dio: ^5.9.0
  flutter_native_splash: 2.4.0
  dartz: ^0.10.1
  flutter_svg: ^2.0.13
  flutter_screenutil: ^5.9.3
  logger: ^2.6.1
  provider: ^6.1.5
  mixpanel_flutter: ^2.4.4
  purchases_ui_flutter: 9.1.0
  purchases_flutter: 9.1.0
  fluttertoast: ^8.2.12
  envied: ^1.2.0
  upgrader: ^11.5.0
  sign_in_with_apple: ^7.0.1
  google_sign_in: ^7.1.1
  in_app_review: ^2.0.10
  video_player: ^2.10.0
  share_plus: ^11.0.0
  url_launcher: ^6.3.2
  clipboard: ^2.0.2
  flutter_secure_storage: ^9.2.4
  uuid: ^4.5.1
  image_picker: ^1.2.0
  toastification: ^3.0.3
  intl:
  gallery_saver_plus:
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.7.0
  flutter_gen_runner: ^5.11.0
  envied_generator: ^1.2.0
  flutter_launcher_icons: ^0.14.4

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/
    - assets/videos/models/
    - assets/icons/

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans-ExtraBold.ttf
          weight: 800

flutter_gen:
  output: lib/core/consts/gen/
  integrations:
    flutter_svg: true
    lottie: true

flutter_native_splash:
  color: "#0a0a0a"
  image: assets/images/lupin_logo.png
  android: true
  ios: true
  android_12:
    color: "#0a0a0a"
    image: assets/images/lupin_logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path_ios: "assets/images/lupin_logo.png"
  image_path_android: "assets/images/lupin_logo.png"
  adaptive_icon_foreground: "assets/images/lupin_logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
